packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/node": ^22.13.14
  "@cloudflare/workers-types": ^4.20251213.0
  hono: ^4.8.2
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.9
  alchemy: ^0.82.1
  "@trpc/client": ^11.7.2
